-- Generated by `python -m db.schema`. Do not edit by hand.

CREATE TABLE IF NOT EXISTS backtests (
	id SERIAL NOT NULL, 
	run_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	strategy VARCHAR(64) NOT NULL, 
	asset VARCHAR(8) NOT NULL, 
	horizon VARCHAR(16) NOT NULL, 
	win_rate FLOAT, 
	avg_r FLOAT, 
	max_drawdown FLOAT, 
	n_trades INTEGER, 
	params JSON, 
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS calendar_events (
	event_id VARCHAR(64) NOT NULL, 
	release_id VARCHAR(32) NOT NULL, 
	name_en TEXT NOT NULL, 
	name_fa TEXT NOT NULL, 
	scheduled_utc TIMESTAMP WITH TIME ZONE NOT NULL, 
	importance INTEGER NOT NULL, 
	date_source VARCHAR(32) NOT NULL, 
	consensus FLOAT, 
	consensus_source VARCHAR(64), 
	previous FLOAT, 
	actual FLOAT, 
	actual_known_at TIMESTAMP WITH TIME ZONE, 
	surprise_z FLOAT, 
	surprise_basis VARCHAR(32), 
	status VARCHAR(16) NOT NULL, 
	PRIMARY KEY (event_id)
);

CREATE INDEX IF NOT EXISTS ix_calendar_scheduled ON calendar_events (scheduled_utc);

CREATE TABLE IF NOT EXISTS candles (
	asset VARCHAR(16) NOT NULL, 
	venue VARCHAR(32) NOT NULL, 
	interval VARCHAR(8) NOT NULL, 
	ts TIMESTAMP WITH TIME ZONE NOT NULL, 
	open FLOAT NOT NULL, 
	high FLOAT NOT NULL, 
	low FLOAT NOT NULL, 
	close FLOAT NOT NULL, 
	volume FLOAT, 
	is_proxy BOOLEAN NOT NULL, 
	PRIMARY KEY (asset, venue, interval, ts)
);

CREATE INDEX IF NOT EXISTS ix_candles_asset_interval_ts ON candles (asset, interval, ts);

CREATE TABLE IF NOT EXISTS derivatives_snapshots (
	asset VARCHAR(16) NOT NULL, 
	venue VARCHAR(32) NOT NULL, 
	ts TIMESTAMP WITH TIME ZONE NOT NULL, 
	open_interest FLOAT, 
	open_interest_usd FLOAT, 
	funding_rate FLOAT, 
	mark_price FLOAT, 
	next_funding_ts TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (asset, venue, ts)
);

CREATE TABLE IF NOT EXISTS features (
	feature_key VARCHAR(64) NOT NULL, 
	obs_date DATE NOT NULL, 
	value FLOAT NOT NULL, 
	computed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (feature_key, obs_date)
);

CREATE TABLE IF NOT EXISTS fed_documents (
	id VARCHAR(40) NOT NULL, 
	doc_type VARCHAR(32) NOT NULL, 
	published_utc TIMESTAMP WITH TIME ZONE, 
	title TEXT NOT NULL, 
	url TEXT NOT NULL, 
	text TEXT, 
	hawkish_score FLOAT, 
	classified_at TIMESTAMP WITH TIME ZONE, 
	classifier_model VARCHAR(64), 
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS fetch_log (
	id SERIAL NOT NULL, 
	run_id VARCHAR(40) NOT NULL, 
	job VARCHAR(32) NOT NULL, 
	target VARCHAR(128) NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	finished_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	status VARCHAR(8) NOT NULL, 
	rows INTEGER, 
	message TEXT, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_fetch_log_run_target UNIQUE (run_id, target)
);

CREATE TABLE IF NOT EXISTS futures_quotes (
	contract VARCHAR(32) NOT NULL, 
	quote_ts TIMESTAMP WITH TIME ZONE NOT NULL, 
	root VARCHAR(8) NOT NULL, 
	contract_month DATE NOT NULL, 
	price FLOAT NOT NULL, 
	implied_rate FLOAT NOT NULL, 
	PRIMARY KEY (contract, quote_ts)
);

CREATE TABLE IF NOT EXISTS impact_coefficients (
	computed_on DATE NOT NULL, 
	indicator VARCHAR(64) NOT NULL, 
	asset VARCHAR(8) NOT NULL, 
	horizon VARCHAR(16) NOT NULL, 
	sample VARCHAR(32) NOT NULL, 
	bucket VARCHAR(8) NOT NULL, 
	coefficient FLOAT NOT NULL, 
	effect_per_sigma FLOAT, 
	t_stat FLOAT, 
	hit_rate FLOAT, 
	n INTEGER, 
	confidence VARCHAR(8), 
	details JSON, 
	PRIMARY KEY (computed_on, indicator, asset, horizon, sample)
);

CREATE TABLE IF NOT EXISTS liquidations (
	raw_id VARCHAR(160) NOT NULL, 
	venue VARCHAR(32) NOT NULL, 
	asset VARCHAR(16) NOT NULL, 
	ts TIMESTAMP WITH TIME ZONE NOT NULL, 
	side VARCHAR(8) NOT NULL, 
	price FLOAT NOT NULL, 
	qty FLOAT, 
	usd FLOAT, 
	PRIMARY KEY (raw_id)
);

CREATE INDEX IF NOT EXISTS ix_liquidations_asset_ts ON liquidations (asset, ts);

CREATE TABLE IF NOT EXISTS news_items (
	id VARCHAR(40) NOT NULL, 
	source VARCHAR(64) NOT NULL, 
	published_utc TIMESTAMP WITH TIME ZONE, 
	title TEXT NOT NULL, 
	url TEXT NOT NULL, 
	summary TEXT, 
	relevance_btc FLOAT, 
	relevance_gold FLOAT, 
	direction_btc INTEGER, 
	direction_gold INTEGER, 
	importance INTEGER, 
	classified_at TIMESTAMP WITH TIME ZONE, 
	classifier_model VARCHAR(64), 
	PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_news_published ON news_items (published_utc);

CREATE TABLE IF NOT EXISTS observation_vintages (
	series_key VARCHAR(64) NOT NULL, 
	obs_date DATE NOT NULL, 
	realtime_start DATE NOT NULL, 
	realtime_end DATE, 
	value FLOAT NOT NULL, 
	PRIMARY KEY (series_key, obs_date, realtime_start)
);

CREATE TABLE IF NOT EXISTS observations (
	series_key VARCHAR(64) NOT NULL, 
	obs_date DATE NOT NULL, 
	value FLOAT NOT NULL, 
	fetched_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (series_key, obs_date)
);

CREATE TABLE IF NOT EXISTS orderbook_snapshots (
	asset VARCHAR(16) NOT NULL, 
	ts TIMESTAMP WITH TIME ZONE NOT NULL, 
	bucket_size FLOAT NOT NULL, 
	mid_price FLOAT, 
	venues JSON NOT NULL, 
	depth JSON NOT NULL, 
	PRIMARY KEY (asset, ts)
);

CREATE TABLE IF NOT EXISTS regime_states (
	model VARCHAR(32) NOT NULL, 
	obs_date DATE NOT NULL, 
	regime VARCHAR(16) NOT NULL, 
	probabilities JSON NOT NULL, 
	computed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (model, obs_date)
);

CREATE TABLE IF NOT EXISTS reports (
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	kind VARCHAR(32) NOT NULL, 
	trigger VARCHAR(64), 
	body_fa TEXT NOT NULL, 
	data JSON, 
	sent_telegram BOOLEAN NOT NULL, 
	PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_reports_created ON reports (created_at);

CREATE TABLE IF NOT EXISTS series_meta (
	key VARCHAR(64) NOT NULL, 
	name_en TEXT NOT NULL, 
	name_fa TEXT NOT NULL, 
	category VARCHAR(32) NOT NULL, 
	source VARCHAR(32) NOT NULL, 
	source_id VARCHAR(128) NOT NULL, 
	url TEXT NOT NULL, 
	units VARCHAR(64) NOT NULL, 
	frequency VARCHAR(16) NOT NULL, 
	release_lag_days INTEGER NOT NULL, 
	max_stale_days INTEGER NOT NULL, 
	proxy BOOLEAN NOT NULL, 
	proxy_for TEXT, 
	last_fetched_at TIMESTAMP WITH TIME ZONE, 
	last_obs_date DATE, 
	source_last_updated TIMESTAMP WITH TIME ZONE, 
	last_status VARCHAR(16), 
	last_message TEXT, 
	PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS signals (
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	asset VARCHAR(8) NOT NULL, 
	direction VARCHAR(8) NOT NULL, 
	horizon VARCHAR(16) NOT NULL, 
	entry_low FLOAT, 
	entry_high FLOAT, 
	stop_loss FLOAT, 
	tp1 FLOAT, 
	tp2 FLOAT, 
	tp3 FLOAT, 
	rr JSON, 
	win_rate FLOAT, 
	confidence VARCHAR(8), 
	invalidation TEXT, 
	reasons JSON, 
	backtest_id INTEGER, 
	status VARCHAR(16) NOT NULL, 
	PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_signals_created ON signals (created_at);
