-- Generated by `python -m db.schema 003_phase2.sql`. Do not edit by hand.

CREATE TABLE IF NOT EXISTS fed_stance (
	obs_date DATE NOT NULL, 
	score FLOAT, 
	components JSON NOT NULL, 
	inputs JSON NOT NULL, 
	computed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (obs_date)
);

ALTER TABLE public.fed_stance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS read_only ON public.fed_stance;
CREATE POLICY read_only ON public.fed_stance FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS fedwatch (
	computed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	meeting_date DATE NOT NULL, 
	implied_rate_after FLOAT NOT NULL, 
	expected_change_bp FLOAT NOT NULL, 
	p_cut FLOAT NOT NULL, 
	p_hold FLOAT NOT NULL, 
	p_hike FLOAT NOT NULL, 
	cumulative_vs_today_bp FLOAT NOT NULL, 
	target_range_probs JSON NOT NULL, 
	method VARCHAR(32) NOT NULL, 
	PRIMARY KEY (computed_at, meeting_date)
);

ALTER TABLE public.fedwatch ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS read_only ON public.fedwatch;
CREATE POLICY read_only ON public.fedwatch FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS inversion_episodes (
	spread_key VARCHAR(32) NOT NULL, 
	start_date DATE NOT NULL, 
	end_date DATE, 
	duration_days INTEGER NOT NULL, 
	depth FLOAT NOT NULL, 
	depth_date DATE NOT NULL, 
	resteepen_date DATE, 
	label TEXT, 
	computed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (spread_key, start_date)
);

ALTER TABLE public.inversion_episodes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS read_only ON public.inversion_episodes;
CREATE POLICY read_only ON public.inversion_episodes FOR SELECT TO anon, authenticated USING (true);
