-- Generated by `python -m db.schema 004_phase3.sql`. Do not edit by hand.

CREATE TABLE IF NOT EXISTS macro_scores (
	computed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	asset VARCHAR(8) NOT NULL, 
	bucket VARCHAR(8) NOT NULL, 
	score FLOAT, 
	contributions JSON NOT NULL, 
	note TEXT, 
	PRIMARY KEY (computed_at, asset, bucket)
);

ALTER TABLE public.macro_scores ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS read_only ON public.macro_scores;
CREATE POLICY read_only ON public.macro_scores FOR SELECT TO anon, authenticated USING (true);
